port 1194
proto udp
dev tun0

# Certificates
ca /etc/openvpn/certs/ca.crt
cert /etc/openvpn/certs/CE3.crt
key /etc/openvpn/certs/CE3.key
dh /etc/openvpn/certs/dh.pem
tls-auth /etc/openvpn/certs/ta.key 0

# Overlay 
server 192.168.100.0 255.255.255.0
topology subnet

# Local routes
route 192.168.11.0 255.255.255.0
route 192.168.22.0 255.255.255.0
route 192.168.32.0 255.255.255.0
route 192.168.95.0 255.255.255.0

# Pushing routes to clients
push "route 192.168.33.0 255.255.255.0"
push "route 192.168.11.0 255.255.255.0"
push "route 192.168.22.0 255.255.255.0"
push "route 192.168.32.0 255.255.255.0"
push "route 192.168.95.0 255.255.255.0"

# Directives for Hub-and-Spoke topology
client-config-dir /etc/openvpn/ccd
client-to-client

keepalive 10 120
cipher AES-256-GCM
persist-key
persist-tun
status /var/log/openvpn-status.log
verb 3
