interface=br0
driver=wired
ieee8021x=1
use_pae_group_addr=1
own_ip_addr=192.168.22.2
auth_server_addr=192.168.33.10
auth_server_port=1812
auth_server_shared_secret=sharedsecret123
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
